name: CI for Dots and Boxes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job pour tester sur plusieurs versions de Python
  test:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour exécuter les tests

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Teste sur plusieurs versions de Python

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Utiliser la dernière version stable de l'action checkout

    # Installer Poetry
    - name: Set up Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    # Installer les dépendances avec Poetry
    - name: Install dependencies
      run: |
        poetry install

    # Exécuter les tests unitaires
    - name: Run unit tests
      run: |
        poetry run python -m unittest discover

  # Job pour l'analyse statique du code avec Flake8
  flake8:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Utiliser la dernière version stable de l'action checkout

    # Installer Poetry et Flake8
    - name: Set up Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Install dependencies and Flake8
      run: |
        poetry install
        poetry run pip install flake8  # Installer Flake8 via Poetry

    # Exécuter Flake8 pour l'analyse statique du code
    - name: Run Flake8
      run: |
        poetry run flake8 .  # Lancer Flake8 sur tout le projet

  # Job pour vérifier la présence de secrets dans le code avec super-linter
  git-secrets:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run GitHub Super Linter for secrets
      uses: github/super-linter@v5
      env:
        RUN_LOCAL: true
        LINTER_RULES_PATH: .github/linters  # Personnaliser les règles si nécessaire