name: Python tests

on:
  push:
    branches:
      - main  # Ou la branche sur laquelle tu veux que les tests se déclenchent
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]  # Matrice avec 2 versions de Python valides

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry and dependencies
      run: |
        python -m pip install --upgrade pip  # Met à jour pip
        python -m pip install poetry  # Installe Poetry
        poetry lock  # Met à jour poetry.lock
        poetry install

    - name: Run Flake8
      run: |
        poetry run flake8 .

    - name: Run unit tests
      run: |
        poetry run python -m unittest discover
